export const dummyProducts = {
  items: [
    {
      no_of_boxes: 1,
      net_quantity: {
        value: 1.0,
        unit: "kg",
      },
      multi_size: true,
      product_publish: {
        is_set: false,
        product_online_date: 1725267498,
      },
      country_of_origin: "India",
      category_slug: "basmati--rice-l3",
      action: "upsert",
      slug: "independence-long-grain-rice-1-kg-pch-7936658",
      return_config: {
        returnable: true,
        time: 1,
        unit: "days",
      },
      is_set: false,
      name: "Independence  Long Grain Rice 1 Kg Pch",
      is_image_less_product: true,
      is_dependent: false,
      currency: "INR",
      tags: ["Staples"],
      brand_uid: 4015,
      custom_order: {
        manufacturing_time_unit: "days",
        is_custom_order: false,
        manufacturing_time: 0,
      },
      departments: [9],
      item_type: "standard",
      item_code: "494260420",
      template_tag: "basmati-rice",
      category_uid: 1106,
      "net-quantity": "1",
      variants: {},
      created_on: "2024-08-30T11:13:57.955000",
      created_by: {
        username: "aanchal1_saxena_ril_com_05159",
        user_id: "b5806f48cb6afd7dad6ab584",
        super_user: false,
      },
      modified_on: "2024-09-02T08:58:19.993000",
      modified_by: {
        username: "yashrajsingh_fynd_external_com_73458",
        user_id: "c90f30c6d7397aadc245d55a",
        super_user: false,
      },
      stage: "pending",
      uid: 7936658,
      all_company_ids: [102],
      all_identifiers: ["494260420"],
      all_sizes: [
        {
          item_width: 5.0,
          company_id: 102,
          size: "OS",
          item_height: 20.0,
          track_inventory: true,
          price: {
            marked: {
              min: 110.0,
              max: 110.0,
            },
            effective: {
              min: 110.0,
              max: 110.0,
            },
          },
          seller_identifier: "494260420",
          identifiers: [
            {
              gtin_value: "494260420",
              gtin_type: "sku_code",
              primary: true,
            },
          ],
          item_length: 100.0,
          brand_uid: 4015,
          price_transfer: 0.0,
          item_weight: 1000.0,
          item_code: "494260420",
          sellable: true,
        },
      ],
      _custom_json: {},
      description: "",
      highlights: [],
      media: [],
      product_group_tag: [],
      short_description: "",
      size_guide: "",
      teaser_tag: {},
      variant_media: {},
      is_active: true,
      tax_identifier: {
        hsn_code_id: "62d004adbe05ede3bf240b64",
        reporting_hsn: "10063020H1",
        hsn_code: "10063020",
      },
      sizes: [],
      id: "66d1a975dd85f9c984ed492e",
      brand: {
        name: "Independence",
        logo: {
          aspect_ratio: "1:1",
          aspect_ratio_f: 1.0,
          url: "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/brands/pictures/square-logo/50x0/vgw-JJAI--Logo.png",
          secure_url:
            "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/brands/pictures/square-logo/50x0/vgw-JJAI--Logo.png",
        },
        uid: 4015,
      },
      images: [],
      price: {
        marked: {
          min: 110.0,
          max: 110.0,
        },
        effective: {
          min: 110.0,
          max: 110.0,
        },
      },
      status: "pending",
      is_expirable: false,
      hsn_code: "62d004adbe05ede3bf240b64",
    },
    {
      brand_uid: 4015,
      is_image_less_product: true,
      category_slug: "basmati--rice-l3",
      product_publish: {
        product_online_date: 1725016385,
        is_set: false,
      },
      country_of_origin: "India",
      is_dependent: false,
      no_of_boxes: 1,
      departments: [9],
      is_set: false,
      multi_size: true,
      slug: "independence-biryani-special-basmati-rice-30kg-bag-7936657",
      name: "Independence Biryani Special Basmati Rice 30Kg Bag",
      tags: ["Staples"],
      custom_order: {
        manufacturing_time: 0,
        is_custom_order: false,
        manufacturing_time_unit: "days",
      },
      return_config: {
        time: 1,
        returnable: true,
        unit: "days",
      },
      currency: "INR",
      net_quantity: {
        value: 30.0,
        unit: "kg",
      },
      item_code: "494260423",
      action: "upsert",
      item_type: "standard",
      template_tag: "basmati-rice",
      category_uid: 1106,
      "net-quantity": "30",
      variants: {},
      created_on: "2024-08-30T11:13:09.188000",
      created_by: {
        username: "aanchal1_saxena_ril_com_05159",
        user_id: "b5806f48cb6afd7dad6ab584",
        super_user: false,
      },
      modified_on: "2024-08-30T11:13:09.188000",
      modified_by: {
        username: "aanchal1_saxena_ril_com_05159",
        user_id: "b5806f48cb6afd7dad6ab584",
        super_user: false,
      },
      stage: "pending",
      uid: 7936657,
      all_company_ids: [102],
      all_identifiers: ["494260423"],
      all_sizes: [
        {
          brand_uid: 4015,
          track_inventory: true,
          item_length: 100.0,
          item_width: 5.0,
          company_id: 102,
          identifiers: [
            {
              gtin_value: "494260423",
              gtin_type: "sku_code",
              primary: true,
            },
          ],
          seller_identifier: "494260423",
          size: "OS",
          price_transfer: 0.0,
          price: {
            marked: {
              min: 5200.0,
              max: 5200.0,
            },
            effective: {
              min: 5200.0,
              max: 5200.0,
            },
          },
          item_code: "494260423",
          item_weight: 30000.0,
          item_height: 20.0,
          sellable: true,
        },
      ],
      is_active: true,
      tax_identifier: {
        hsn_code_id: "62d004adbe05ede3bf240b64",
        reporting_hsn: "10063020H1",
        hsn_code: "10063020",
      },
      sizes: [],
      id: "66d1a945b74670cc96e1499a",
      brand: {
        name: "Independence",
        logo: {
          aspect_ratio: "1:1",
          aspect_ratio_f: 1.0,
          url: "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/brands/pictures/square-logo/50x0/vgw-JJAI--Logo.png",
          secure_url:
            "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/brands/pictures/square-logo/50x0/vgw-JJAI--Logo.png",
        },
        uid: 4015,
      },
      media: [],
      images: [],
      price: {
        marked: {
          min: 5200.0,
          max: 5200.0,
        },
        effective: {
          min: 5200.0,
          max: 5200.0,
        },
      },
      status: "pending",
      is_expirable: false,
      hsn_code: "62d004adbe05ede3bf240b64",
    },
    {
      tags: ["Staples"],
      country_of_origin: "India",
      slug: "independence-long-grain-rice-5-kg-pch-7936656",
      is_dependent: false,
      custom_order: {
        manufacturing_time_unit: "days",
        manufacturing_time: 0,
        is_custom_order: false,
      },
      net_quantity: {
        unit: "kg",
        value: 5.0,
      },
      name: "Independence Long Grain Rice 5 Kg Pch",
      is_set: false,
      item_code: "493721176",
      currency: "INR",
      is_image_less_product: true,
      departments: [9],
      product_publish: {
        is_set: false,
        product_online_date: 1725016385,
      },
      item_type: "standard",
      multi_size: true,
      category_slug: "basmati--rice-l3",
      action: "upsert",
      brand_uid: 4015,
      return_config: {
        unit: "days",
        returnable: true,
        time: 1,
      },
      no_of_boxes: 1,
      template_tag: "basmati-rice",
      category_uid: 1106,
      "net-quantity": "5",
      variants: {},
      created_on: "2024-08-30T11:13:09.079000",
      created_by: {
        username: "aanchal1_saxena_ril_com_05159",
        user_id: "b5806f48cb6afd7dad6ab584",
        super_user: false,
      },
      modified_on: "2024-08-30T11:13:09.079000",
      modified_by: {
        username: "aanchal1_saxena_ril_com_05159",
        user_id: "b5806f48cb6afd7dad6ab584",
        super_user: false,
      },
      stage: "pending",
      uid: 7936656,
      all_company_ids: [102],
      all_identifiers: ["493721176"],
      all_sizes: [
        {
          price: {
            marked: {
              min: 520.0,
              max: 520.0,
            },
            effective: {
              min: 520.0,
              max: 520.0,
            },
          },
          size: "OS",
          item_height: 20.0,
          price_transfer: 0.0,
          company_id: 102,
          item_weight: 5000.0,
          item_code: "493721176",
          item_width: 5.0,
          identifiers: [
            {
              gtin_type: "sku_code",
              gtin_value: "493721176",
              primary: true,
            },
          ],
          seller_identifier: "493721176",
          track_inventory: true,
          brand_uid: 4015,
          item_length: 100.0,
          sellable: true,
        },
      ],
      is_active: true,
      tax_identifier: {
        hsn_code_id: "62d004adbe05ede3bf240b64",
        reporting_hsn: "10063020H1",
        hsn_code: "10063020",
      },
      sizes: [],
      id: "66d1a945fbf3e76348f60bb7",
      brand: {
        name: "Independence",
        logo: {
          aspect_ratio: "1:1",
          aspect_ratio_f: 1.0,
          url: "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/brands/pictures/square-logo/50x0/vgw-JJAI--Logo.png",
          secure_url:
            "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/brands/pictures/square-logo/50x0/vgw-JJAI--Logo.png",
        },
        uid: 4015,
      },
      media: [],
      images: [],
      price: {
        marked: {
          min: 520.0,
          max: 520.0,
        },
        effective: {
          min: 520.0,
          max: 520.0,
        },
      },
      status: "pending",
      is_expirable: false,
      hsn_code: "62d004adbe05ede3bf240b64",
    },
    {
      country_of_origin: "India",
      action: "upsert",
      no_of_boxes: 1,
      item_type: "standard",
      return_config: {
        unit: "days",
        time: 1,
        returnable: true,
      },
      departments: [9],
      is_set: false,
      product_publish: {
        is_set: false,
        product_online_date: 1725016385,
      },
      brand_uid: 4015,
      slug: "independence-rozana-basmati-rice-1-kg-bg-7936655",
      net_quantity: {
        value: 1.0,
        unit: "kg",
      },
      is_dependent: false,
      category_slug: "basmati--rice-l3",
      is_image_less_product: true,
      name: "Independence  Rozana Basmati Rice 1 Kg Bg",
      custom_order: {
        is_custom_order: false,
        manufacturing_time: 0,
        manufacturing_time_unit: "days",
      },
      currency: "INR",
      multi_size: true,
      item_code: "494260421",
      tags: ["Staples"],
      template_tag: "basmati-rice",
      category_uid: 1106,
      "net-quantity": "1",
      variants: {},
      created_on: "2024-08-30T11:13:08.941000",
      created_by: {
        username: "aanchal1_saxena_ril_com_05159",
        user_id: "b5806f48cb6afd7dad6ab584",
        super_user: false,
      },
      modified_on: "2024-08-30T11:13:08.941000",
      modified_by: {
        username: "aanchal1_saxena_ril_com_05159",
        user_id: "b5806f48cb6afd7dad6ab584",
        super_user: false,
      },
      stage: "pending",
      uid: 7936655,
      all_company_ids: [102],
      all_identifiers: ["494260421"],
      all_sizes: [
        {
          item_length: 100.0,
          company_id: 102,
          price_transfer: 0.0,
          brand_uid: 4015,
          item_weight: 1000.0,
          item_width: 5.0,
          seller_identifier: "494260421",
          track_inventory: true,
          size: "OS",
          item_height: 20.0,
          identifiers: [
            {
              primary: true,
              gtin_type: "sku_code",
              gtin_value: "494260421",
            },
          ],
          price: {
            marked: {
              min: 120.0,
              max: 120.0,
            },
            effective: {
              min: 120.0,
              max: 120.0,
            },
          },
          item_code: "494260421",
          sellable: true,
        },
      ],
      is_active: true,
      tax_identifier: {
        hsn_code_id: "62d004adbe05ede3bf240b64",
        reporting_hsn: "10063020H1",
        hsn_code: "10063020",
      },
      sizes: [],
      id: "66d1a944cda4d5092dfebfad",
      brand: {
        name: "Independence",
        logo: {
          aspect_ratio: "1:1",
          aspect_ratio_f: 1.0,
          url: "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/brands/pictures/square-logo/50x0/vgw-JJAI--Logo.png",
          secure_url:
            "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/brands/pictures/square-logo/50x0/vgw-JJAI--Logo.png",
        },
        uid: 4015,
      },
      media: [],
      images: [],
      price: {
        marked: {
          min: 120.0,
          max: 120.0,
        },
        effective: {
          min: 120.0,
          max: 120.0,
        },
      },
      status: "pending",
      is_expirable: false,
      hsn_code: "62d004adbe05ede3bf240b64",
    },
    {
      name: "Independence Rozana Basmati Rice 5 Kg Bag",
      is_image_less_product: true,
      currency: "INR",
      custom_order: {
        is_custom_order: false,
        manufacturing_time: 0,
        manufacturing_time_unit: "days",
      },
      product_publish: {
        is_set: false,
        product_online_date: 1725016385,
      },
      action: "upsert",
      is_dependent: false,
      net_quantity: {
        value: 5.0,
        unit: "kg",
      },
      tags: ["Staples"],
      slug: "independence-rozana-basmati-rice-5-kg-bag-7936654",
      item_type: "standard",
      category_slug: "basmati--rice-l3",
      brand_uid: 4015,
      multi_size: true,
      country_of_origin: "India",
      is_set: false,
      departments: [9],
      return_config: {
        time: 1,
        unit: "days",
        returnable: true,
      },
      no_of_boxes: 1,
      item_code: "493721178",
      template_tag: "basmati-rice",
      category_uid: 1106,
      "net-quantity": "5",
      variants: {},
      created_on: "2024-08-30T11:13:08.422000",
      created_by: {
        username: "aanchal1_saxena_ril_com_05159",
        user_id: "b5806f48cb6afd7dad6ab584",
        super_user: false,
      },
      modified_on: "2024-08-30T11:13:08.422000",
      modified_by: {
        username: "aanchal1_saxena_ril_com_05159",
        user_id: "b5806f48cb6afd7dad6ab584",
        super_user: false,
      },
      stage: "pending",
      uid: 7936654,
      all_company_ids: [102],
      all_identifiers: ["493721178"],
      all_sizes: [
        {
          identifiers: [
            {
              primary: true,
              gtin_type: "sku_code",
              gtin_value: "493721178",
            },
          ],
          item_weight: 5000.0,
          price: {
            marked: {
              min: 580.0,
              max: 580.0,
            },
            effective: {
              min: 580.0,
              max: 580.0,
            },
          },
          seller_identifier: "493721178",
          item_height: 20.0,
          price_transfer: 0.0,
          brand_uid: 4015,
          track_inventory: true,
          size: "OS",
          item_width: 5.0,
          company_id: 102,
          item_length: 100.0,
          item_code: "493721178",
          sellable: true,
        },
      ],
      is_active: true,
      tax_identifier: {
        hsn_code_id: "62d004adbe05ede3bf240b64",
        reporting_hsn: "10063020H1",
        hsn_code: "10063020",
      },
      sizes: [],
      id: "66d1a944ff0ede7defbef195",
      brand: {
        name: "Independence",
        logo: {
          aspect_ratio: "1:1",
          aspect_ratio_f: 1.0,
          url: "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/brands/pictures/square-logo/50x0/vgw-JJAI--Logo.png",
          secure_url:
            "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/brands/pictures/square-logo/50x0/vgw-JJAI--Logo.png",
        },
        uid: 4015,
      },
      media: [],
      images: [],
      price: {
        marked: {
          min: 580.0,
          max: 580.0,
        },
        effective: {
          min: 580.0,
          max: 580.0,
        },
      },
      status: "pending",
      is_expirable: false,
      hsn_code: "62d004adbe05ede3bf240b64",
    },
    {
      no_of_boxes: 1,
      net_quantity: {
        value: 1.0,
        unit: "kg",
      },
      multi_size: false,
      _custom_json: {},
      product_publish: {
        is_set: false,
        product_online_date: 1724757467,
      },
      country_of_origin: "India",
      category_slug: "basmati--rice-l3",
      slug: "ind-super-basmati-rice-1-kg-pch-n-7936591",
      teaser_tag: {},
      return_config: {
        returnable: false,
        time: 0,
        unit: "days",
      },
      product_group_tag: [],
      is_set: false,
      name: "IND SUPER BASMATI RICE 1 KG PCH N",
      variant_media: {},
      is_image_less_product: false,
      is_dependent: false,
      currency: "INR",
      short_description: "",
      tags: ["FMCG"],
      brand_uid: 4015,
      custom_order: {
        manufacturing_time_unit: "days",
        is_custom_order: false,
        manufacturing_time: 0,
      },
      media: [
        {
          url: "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/products/pictures/item/free/135x0/wOYYeDqx5-IND-SUPER-BASMATI-RICE-1-KG-PCH-N.png",
          type: "image",
        },
        {
          url: "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/products/pictures/item/free/135x0/BgOpbCFu0-IND-SUPER-BASMATI-RICE-1-KG-PCH-N.png",
          type: "image",
        },
      ],
      departments: [9],
      highlights: [],
      item_type: "standard",
      size_guide: "",
      description: "",
      item_code: "493721180",
      template_tag: "basmati-rice",
      category_uid: 1106,
      "net-quantity": "1 KG",
      variants: {},
      created_on: "2024-08-27T11:17:49.485000",
      created_by: {
        username: "aanchal1_saxena_ril_com_05159",
        user_id: "b5806f48cb6afd7dad6ab584",
        super_user: false,
      },
      modified_on: "2024-08-27T11:17:49.485000",
      modified_by: {
        username: "aanchal1_saxena_ril_com_05159",
        user_id: "b5806f48cb6afd7dad6ab584",
        super_user: false,
      },
      stage: "pending",
      uid: 7936591,
      all_company_ids: [102],
      all_identifiers: ["493721180"],
      all_sizes: [
        {
          item_width: 2.0,
          _custom_json: {},
          company_id: 102,
          size: "OS",
          item_height: 10.0,
          track_inventory: false,
          price: {
            marked: {
              min: 180.0,
              max: 180.0,
            },
            effective: {
              min: 180.0,
              max: 180.0,
            },
          },
          seller_identifier: "493721180",
          identifiers: [
            {
              gtin_value: "493721180",
              gtin_type: "ean",
              primary: true,
            },
          ],
          item_length: 25.0,
          brand_uid: 4015,
          price_transfer: 0.0,
          item_weight: 1000.0,
          item_code: "493721180",
          sellable: true,
        },
      ],
      is_active: true,
      tax_identifier: {
        hsn_code_id: "63b421f6b5c3204c1dd3b65a",
        reporting_hsn: "10063020H2",
        hsn_code: "10063020",
      },
      sizes: [],
      id: "66cdb5dddd85f9c984ed48fa",
      brand: {
        name: "Independence",
        logo: {
          aspect_ratio: "1:1",
          aspect_ratio_f: 1.0,
          url: "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/brands/pictures/square-logo/50x0/vgw-JJAI--Logo.png",
          secure_url:
            "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/brands/pictures/square-logo/50x0/vgw-JJAI--Logo.png",
        },
        uid: 4015,
      },
      images: [
        {
          aspect_ratio: "16:25",
          aspect_ratio_f: 0.64,
          url: "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/products/pictures/item/free/135x0/wOYYeDqx5-IND-SUPER-BASMATI-RICE-1-KG-PCH-N.png",
          secure_url:
            "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/products/pictures/item/free/135x0/wOYYeDqx5-IND-SUPER-BASMATI-RICE-1-KG-PCH-N.png",
        },
        {
          aspect_ratio: "16:25",
          aspect_ratio_f: 0.64,
          url: "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/products/pictures/item/free/135x0/BgOpbCFu0-IND-SUPER-BASMATI-RICE-1-KG-PCH-N.png",
          secure_url:
            "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/products/pictures/item/free/135x0/BgOpbCFu0-IND-SUPER-BASMATI-RICE-1-KG-PCH-N.png",
        },
      ],
      price: {
        marked: {
          min: 180.0,
          max: 180.0,
        },
        effective: {
          min: 180.0,
          max: 180.0,
        },
      },
      status: "pending",
      is_expirable: false,
      hsn_code: "63b421f6b5c3204c1dd3b65a",
    },
    {
      multi_size: false,
      no_of_boxes: 1,
      name: "Campa Cola Zero 330ml Can",
      product_publish: {
        is_set: false,
        product_online_date: 1724665499,
      },
      item_type: "standard",
      custom_order: {
        is_custom_order: false,
        manufacturing_time: 0,
        manufacturing_time_unit: "days",
      },
      country_of_origin: "India",
      slug: "campa-cola-zero-330ml-can-7544633-7622516",
      brand_uid: 119933,
      media: [
        {
          url: "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/products/pictures/item/free/135x0/campa-zero/493680315/0/B7B-C-mMjQ-u2nJRve4_-Campa-Cola-Zero-200-ml-Can.png",
          type: "image",
        },
      ],
      item_code: "493680315",
      tags: ["BEVERAGES"],
      is_image_less_product: false,
      category_slug: "cold-drinks1",
      is_set: false,
      return_config: {
        time: 0,
        unit: "days",
        returnable: false,
      },
      departments: [9],
      is_dependent: false,
      currency: "INR",
      action: "upsert",
      template_tag: "cold-drinks1",
      category_uid: 140139,
      "reporting-hsn": "81350200",
      variants: {},
      created_on: "2024-03-08T16:01:08.062000",
      created_by: {
        username: "rockypatro_gofynd_com_03246",
        user_id: "cff976a38a69bbafb606a395",
        super_user: false,
      },
      modified_on: "2024-08-26T09:45:00.704000",
      modified_by: {
        username: "kakkuppi_ganesh_ril_com_64969",
        user_id: "db6ef475672c87290e9ab6d7",
        super_user: false,
      },
      stage: "pending",
      uid: 7622516,
      all_company_ids: [1, 102],
      all_identifiers: ["000000000493680315", "493680315"],
      all_sizes: [
        {
          item_length: 10.0,
          item_weight: 10.0,
          company_id: 102,
          identifiers: [
            {
              gtin_value: "493680315",
              gtin_type: "sku_code",
              primary: true,
            },
          ],
          price: {
            marked: {
              min: 100.0,
              max: 100.0,
            },
            effective: {
              min: 100.0,
              max: 100.0,
            },
          },
          _custom_json: {},
          item_width: 10.0,
          item_height: 10.0,
          seller_identifier: "493680315",
          size: "OS",
          item_code: "493680315",
          track_inventory: true,
          brand_uid: 119933,
          price_transfer: 0.0,
          sellable: true,
        },
      ],
      _custom_json: {},
      description: "",
      highlights: [],
      net_quantity: {},
      product_group_tag: [],
      short_description: "",
      size_guide: "",
      teaser_tag: {},
      variant_media: {},
      "net-quantity": "330ml",
      is_active: true,
      tax_identifier: {
        hsn_code_id: "664cdcbbf4f3e5e9a3f6a52d",
        reporting_hsn: "2024174183H1",
        hsn_code: "2024174183",
      },
      sizes: [
        {
          size: "OS",
          store_count: 3,
          sellable_quantity: 113352,
          sellable: true,
          price: {
            marked: {
              min: 60.0,
              max: 100.0,
            },
            effective: {
              min: 60.0,
              max: 100.0,
            },
          },
          seller_identifier: "493680315",
          price_transfer: 0.0,
          track_inventory: true,
        },
      ],
      id: "65eb3644585f21a5986d3525",
      brand: {
        name: "Brunt Test Brand 1713328451364",
        logo: {
          aspect_ratio: "1:1",
          aspect_ratio_f: 1.0,
          url: "https://cdn.pixelbin.io/v2/falling-surf-7c8bb8/fyndnp/wrkr/x0/brands/pictures/square-logo/50x0/t6nWr4HtV-Logo.png",
          secure_url:
            "https://cdn.pixelbin.io/v2/falling-surf-7c8bb8/fyndnp/wrkr/x0/brands/pictures/square-logo/50x0/t6nWr4HtV-Logo.png",
        },
        uid: 119933,
      },
      images: [
        {
          aspect_ratio: "16:25",
          aspect_ratio_f: 0.64,
          url: "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/products/pictures/item/free/135x0/campa-zero/493680315/0/B7B-C-mMjQ-u2nJRve4_-Campa-Cola-Zero-200-ml-Can.png",
          secure_url:
            "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/products/pictures/item/free/135x0/campa-zero/493680315/0/B7B-C-mMjQ-u2nJRve4_-Campa-Cola-Zero-200-ml-Can.png",
        },
      ],
      price: {
        marked: {
          min: 60.0,
          max: 100.0,
        },
        effective: {
          min: 60.0,
          max: 100.0,
        },
      },
      status: "pending",
      is_expirable: true,
      hsn_code: "664cdcbbf4f3e5e9a3f6a52d",
    },
    {
      name: "Campa Orange 1L PET",
      custom_order: {
        is_custom_order: false,
        manufacturing_time: 0,
        manufacturing_time_unit: "days",
      },
      is_dependent: false,
      is_image_less_product: false,
      tags: ["BEVERAGES"],
      brand_uid: 4021,
      is_set: false,
      return_config: {
        time: 0,
        unit: "days",
        returnable: false,
      },
      departments: [9],
      country_of_origin: "India",
      media: [
        {
          url: "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/products/pictures/item/free/135x0/campa-orange/493680306/0/GvF_BxwfiW-Tn8mrspIT-Campa-Orange-1L-PET.jpeg",
          type: "image",
        },
      ],
      item_code: "493680306",
      action: "upsert",
      no_of_boxes: 1,
      category_slug: "cold-drinks1",
      slug: "campa-orange-1l-pet-7544667-7545845",
      multi_size: false,
      currency: "INR",
      product_publish: {
        is_set: false,
        product_online_date: 1724665456,
      },
      item_type: "standard",
      template_tag: "cold-drinks1",
      category_uid: 140139,
      "reporting-hsn": "81350200",
      variants: {},
      created_on: "2023-12-25T13:46:30.384000",
      created_by: {
        username: "kakkuppi_ganesh_ril_com_64969",
        user_id: "db6ef475672c87290e9ab6d7",
        super_user: false,
      },
      modified_on: "2024-08-26T09:44:17.726000",
      modified_by: {
        username: "kakkuppi_ganesh_ril_com_64969",
        user_id: "db6ef475672c87290e9ab6d7",
        super_user: false,
      },
      stage: "pending",
      uid: 7545845,
      all_company_ids: [1, 102],
      all_identifiers: ["493680306", "000000000493680306"],
      all_sizes: [
        {
          identifiers: [
            {
              primary: true,
              gtin_type: "sku_code",
              gtin_value: "493680306",
            },
          ],
          item_weight: 10.0,
          price: {
            marked: {
              min: 100.0,
              max: 100.0,
            },
            effective: {
              min: 100.0,
              max: 100.0,
            },
          },
          seller_identifier: "493680306",
          item_height: 10.0,
          price_transfer: 0.0,
          brand_uid: 4021,
          track_inventory: false,
          size: "OS",
          item_width: 10.0,
          _custom_json: {},
          company_id: 102,
          item_length: 10.0,
          item_code: "493680306",
          sellable: true,
        },
      ],
      "net-quantity": "1 L",
      net_quantity: {
        value: 1.0,
        unit: "L",
      },
      _custom_json: {},
      description: "",
      highlights: [],
      product_group_tag: [],
      short_description: "",
      size_guide: "",
      teaser_tag: {},
      variant_media: {},
      is_active: true,
      tax_identifier: {
        hsn_code_id: "664cdcbbf4f3e5e9a3f6a52d",
        reporting_hsn: "2024174183H1",
        hsn_code: "2024174183",
      },
      sizes: [],
      id: "658987b61c9f4d7880806e3b",
      brand: {
        name: "Campa Orange",
        logo: {
          aspect_ratio: "1:1",
          aspect_ratio_f: 1.0,
          url: "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/brands/pictures/square-logo/50x0/Cca3buw3V-Logo.png",
          secure_url:
            "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/brands/pictures/square-logo/50x0/Cca3buw3V-Logo.png",
        },
        uid: 4021,
      },
      images: [
        {
          aspect_ratio: "16:25",
          aspect_ratio_f: 0.64,
          url: "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/products/pictures/item/free/135x0/campa-orange/493680306/0/GvF_BxwfiW-Tn8mrspIT-Campa-Orange-1L-PET.jpeg",
          secure_url:
            "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/products/pictures/item/free/135x0/campa-orange/493680306/0/GvF_BxwfiW-Tn8mrspIT-Campa-Orange-1L-PET.jpeg",
        },
      ],
      price: {
        marked: {
          min: 100.0,
          max: 100.0,
        },
        effective: {
          min: 100.0,
          max: 100.0,
        },
      },
      status: "pending",
      is_expirable: true,
      hsn_code: "664cdcbbf4f3e5e9a3f6a52d",
    },
    {
      name: "Campa Cola 200ml Can",
      custom_order: {
        manufacturing_time: 0,
        manufacturing_time_unit: "days",
        is_custom_order: false,
      },
      is_dependent: false,
      is_image_less_product: false,
      tags: ["BEVERAGES"],
      brand_uid: 4018,
      is_set: false,
      return_config: {
        returnable: false,
        time: 0,
        unit: "days",
      },
      departments: [9],
      country_of_origin: "India",
      media: [
        {
          url: "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/products/pictures/item/free/135x0/campa-cola/493661399/0/avu3xBoGax-hyhyBFoUa-Campa-Cola-200ml-Can.jpeg",
          type: "image",
        },
      ],
      item_code: "493661399",
      action: "upsert",
      no_of_boxes: 1,
      category_slug: "cold-drinks1",
      slug: "campa-cola-200ml-can-7544645-7545830",
      multi_size: false,
      currency: "INR",
      product_publish: {
        product_online_date: 1724665400,
        is_set: false,
      },
      item_type: "standard",
      template_tag: "cold-drinks1",
      category_uid: 140139,
      "reporting-hsn": "81350200",
      variants: {},
      created_on: "2023-12-25T13:46:07.850000",
      created_by: {
        username: "kakkuppi_ganesh_ril_com_64969",
        user_id: "db6ef475672c87290e9ab6d7",
        super_user: false,
      },
      modified_on: "2024-08-26T09:43:22.192000",
      modified_by: {
        username: "kakkuppi_ganesh_ril_com_64969",
        user_id: "db6ef475672c87290e9ab6d7",
        super_user: false,
      },
      stage: "pending",
      uid: 7545830,
      all_company_ids: [1, 102],
      all_identifiers: ["493661399", "000000000493661399"],
      all_sizes: [
        {
          company_id: 102,
          size: "OS",
          item_weight: 10.0,
          item_length: 10.0,
          item_width: 10.0,
          track_inventory: false,
          price: {
            marked: {
              min: 100.0,
              max: 100.0,
            },
            effective: {
              min: 100.0,
              max: 100.0,
            },
          },
          item_height: 10.0,
          item_code: "493661399",
          brand_uid: 4018,
          price_transfer: 0.0,
          _custom_json: {},
          seller_identifier: "493661399",
          identifiers: [
            {
              gtin_value: "493661399",
              gtin_type: "sku_code",
              primary: true,
            },
          ],
          sellable: true,
        },
      ],
      "net-quantity": "200 ml",
      net_quantity: {
        value: 200.0,
        unit: "ml",
      },
      _custom_json: {},
      description: "",
      highlights: [],
      product_group_tag: [],
      short_description: "",
      size_guide: "",
      teaser_tag: {},
      variant_media: {},
      is_active: true,
      tax_identifier: {
        hsn_code_id: "664da58ac9bd7e37329a7fe5",
        reporting_hsn: "2024758556H1",
        hsn_code: "2024758556",
      },
      sizes: [
        {
          size: "OS",
          store_count: 1,
          sellable_quantity: 1000,
          sellable: true,
          price: {
            marked: {
              min: 100.0,
              max: 100.0,
            },
            effective: {
              min: 100.0,
              max: 100.0,
            },
          },
          seller_identifier: "493661399",
          price_transfer: 0.0,
          track_inventory: false,
        },
      ],
      id: "6589879f1c9f4d7880806e23",
      brand: {
        name: "Campa Cola",
        logo: {
          aspect_ratio: "1:1",
          aspect_ratio_f: 1.0,
          url: "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/brands/pictures/square-logo/50x0/pUnE8OMkA-tnXkOwaNm-Logo.jpeg",
          secure_url:
            "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/brands/pictures/square-logo/50x0/pUnE8OMkA-tnXkOwaNm-Logo.jpeg",
        },
        uid: 4018,
      },
      images: [
        {
          aspect_ratio: "16:25",
          aspect_ratio_f: 0.64,
          url: "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/products/pictures/item/free/135x0/campa-cola/493661399/0/avu3xBoGax-hyhyBFoUa-Campa-Cola-200ml-Can.jpeg",
          secure_url:
            "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/products/pictures/item/free/135x0/campa-cola/493661399/0/avu3xBoGax-hyhyBFoUa-Campa-Cola-200ml-Can.jpeg",
        },
      ],
      price: {
        marked: {
          min: 100.0,
          max: 100.0,
        },
        effective: {
          min: 100.0,
          max: 100.0,
        },
      },
      status: "pending",
      is_expirable: true,
      hsn_code: "664da58ac9bd7e37329a7fe5",
    },
    {
      tags: [],
      media: [
        {
          url: "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/products/pictures/item/free/135x0/campa-cola/493680309/0/Lnr5Rc42or-5mqIyj78d-Campa-Cola-330ml-Can.jpeg",
          type: "image",
        },
      ],
      country_of_origin: "India",
      slug: "campa-cola-330ml-can-7936590",
      is_dependent: false,
      custom_order: {
        manufacturing_time_unit: "days",
        manufacturing_time: 0,
        is_custom_order: false,
      },
      name: "Campa Cola 330ml Can",
      is_set: false,
      item_code: "493680309",
      currency: "INR",
      is_image_less_product: false,
      departments: [9],
      product_publish: {
        is_set: false,
        product_online_date: 1724665311,
      },
      item_type: "standard",
      multi_size: true,
      category_slug: "cold-drinks1",
      action: "upsert",
      brand_uid: 4018,
      return_config: {
        unit: "days",
        returnable: true,
        time: 6,
      },
      no_of_boxes: 1,
      template_tag: "cold-drinks1",
      category_uid: 140139,
      variants: {},
      created_on: "2024-08-26T09:41:55.024000",
      created_by: {
        username: "kakkuppi_ganesh_ril_com_64969",
        user_id: "db6ef475672c87290e9ab6d7",
        super_user: false,
      },
      modified_on: "2024-08-26T09:41:55.024000",
      modified_by: {
        username: "kakkuppi_ganesh_ril_com_64969",
        user_id: "db6ef475672c87290e9ab6d7",
        super_user: false,
      },
      stage: "pending",
      uid: 7936590,
      all_company_ids: [102],
      all_identifiers: ["493680309"],
      all_sizes: [
        {
          price: {
            marked: {
              min: 1000.0,
              max: 1000.0,
            },
            effective: {
              min: 1000.0,
              max: 1000.0,
            },
          },
          size: "OS",
          item_height: 10.0,
          price_transfer: 0.0,
          company_id: 102,
          item_weight: 100.0,
          item_code: "493680309",
          item_width: 10.0,
          identifiers: [
            {
              gtin_type: "sku_code",
              gtin_value: "493680309",
              primary: true,
            },
          ],
          seller_identifier: "493680309",
          track_inventory: false,
          brand_uid: 4018,
          item_length: 10.0,
          sellable: true,
        },
      ],
      is_active: true,
      tax_identifier: {
        hsn_code_id: "662b50dfac0c1aacfcb7a552",
        reporting_hsn: "00000000H1",
        hsn_code: "00000000",
      },
      sizes: [],
      id: "66cc4de3fbf3e76348f60b7f",
      brand: {
        name: "Campa Cola",
        logo: {
          aspect_ratio: "1:1",
          aspect_ratio_f: 1.0,
          url: "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/brands/pictures/square-logo/50x0/pUnE8OMkA-tnXkOwaNm-Logo.jpeg",
          secure_url:
            "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/brands/pictures/square-logo/50x0/pUnE8OMkA-tnXkOwaNm-Logo.jpeg",
        },
        uid: 4018,
      },
      images: [
        {
          aspect_ratio: "16:25",
          aspect_ratio_f: 0.64,
          url: "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/products/pictures/item/free/135x0/campa-cola/493680309/0/Lnr5Rc42or-5mqIyj78d-Campa-Cola-330ml-Can.jpeg",
          secure_url:
            "https://cdn.pixelbin.io/v2/jiomart-partner/jmp-np/wrkr/jmpx3/products/pictures/item/free/135x0/campa-cola/493680309/0/Lnr5Rc42or-5mqIyj78d-Campa-Cola-330ml-Can.jpeg",
        },
      ],
      price: {
        marked: {
          min: 1000.0,
          max: 1000.0,
        },
        effective: {
          min: 1000.0,
          max: 1000.0,
        },
      },
      status: "pending",
      is_expirable: true,
      hsn_code: "662b50dfac0c1aacfcb7a552",
    },
  ],
};
