import "./globals.css";
import ClientLayout from "./clientLayout";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  //get used d
  return (
    <html lang="en">
      <body className="bg-white text-black">
        <ClientLayout session={session}>{children}</ClientLayout>
      </body>
    </html>
  );
}
